### ISSUE TITLE
Example to post response time metric

### ISSUE THREAD

**Issue by thatarchguy** [imlonghao/cachet.python#1]
I made a simple example for your api client that I found useful.  
This code is used to test the response time for a website and post the data to a metric.

``` python
import requests
import time
from cachet import Cachet

test_url = "yoururl.example.com"
cachet_url = "cachet.example.com/api/v1"
api_token = "deadbeefdeadbeef"

start = time.time()
r = requests.get(test_url)
r.content  # wait until full content has been transferred
roundtrip = time.time() - start
total_time = roundtrip * 1000 # get time in milliseconds

c = Cachet(url=cachet_url, apiToken=api_token)
response = c.postMetricsPointsByID(1, total_time)
print response.content
```

Thank you for writing this library!

**Comment by imlonghao** [comment]
Hi,

I am excited that someone found my code and loved it.
Originally, I wrote `cachet.python` for my small monitor tool just like the code you provided.
I thought nobody else will use this library so I even didn't write the `READMD.md`

I will continue to improve this library.

Thank you.
